In [1]:
# to know whether the new added column is important or not 

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 

In [9]:
data_1 = pd.read_csv('./case2.csv')

In [10]:
data_1

YearsExperience   Salary
0               1.1  39343.0
1               1.3  46205.0
2               1.5  37731.0
3               2.0  43525.0
4               2.2  39891.0
5               2.9  56642.0
6               3.0  60150.0
7               3.2  54445.0
8               3.2  64445.0
9               3.7  57189.0
10              3.9  63218.0
11              4.0  55794.0
12              4.0  56957.0
13              4.1  57081.0
14              4.5  61111.0

In [11]:
data_1.shape

(15, 2)

In [12]:
data_1['YearsExperience'].shape

(15,)

In [14]:
a = np.arange(21,31)
a

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [15]:
a.shape

(10,)

In [16]:
# reshape

c = a.reshape(-1,1)
c

array([[21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30]])

In [17]:
c.shape

(10, 1)

In [18]:
b = np.arange(21,31)
b

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [19]:
b.shape

(10,)

In [20]:
c = b.reshape(1,-1)
c

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [21]:
c.shape

(1, 10)

In [22]:
X = data_1['YearsExperience']
y = data_1['Salary']

In [23]:
X.shape

(15,)

In [26]:
X = X.reshape(-1,1)
X

array([[1.1],
       [1.3],
       [1.5],
       [2. ],
       [2.2],
       [2.9],
       [3. ],
       [3.2],
       [3.2],
       [3.7],
       [3.9],
       [4. ],
       [4. ],
       [4.1],
       [4.5]])

In [27]:
X.shape

(15, 1)

In [32]:
X.shape[0]

15

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
reg = LinearRegression()

In [30]:
reg.fit(X,y)

LinearRegression()

In [31]:
reg.score(X,y) # r2

0.7020755183418668

In [ ]:
# 1 - (1 - r2)(n-1) / (n-k-1)

In [33]:
data_1.shape

(15, 2)

In [38]:
# Adjusted r2


1 - (1 - reg.score(X,y))*(X.shape[0] - 1) / (X.shape[0] - data_1.shape[1] - 1)

0.6524214380655111

In [39]:
## checking with unwanted added column

In [40]:
data_2 = pd.read_csv('./case.csv')

In [41]:
data_2

YearsExperience   Salary  Height
0               1.1  39343.0    1.47
1               1.3  46205.0    1.50
2               1.5  37731.0    1.52
3               2.0  43525.0    1.55
4               2.2  39891.0    1.57
5               2.9  56642.0    1.60
6               3.0  60150.0    1.63
7               3.2  54445.0    1.65
8               3.2  64445.0    1.68
9               3.7  57189.0    1.70
10              3.9  63218.0    1.73
11              4.0  55794.0    1.75
12              4.0  56957.0    1.78
13              4.1  57081.0    1.80
14              4.5  61111.0    1.83

In [42]:
X = data_2[['YearsExperience' , 'Height']]

In [43]:
y = data_2['Salary']

In [44]:
reg_1 = LinearRegression()

In [45]:
reg_1.fit(X,y)

LinearRegression()

In [47]:
reg_1.score(X,y)

0.7388592596500806

In [48]:
X.shape

(15, 2)

In [49]:
data_2.shape

(15, 3)

In [50]:
# Adjusted r2

1 - (1 - reg_1.score(X,y))*(X.shape[0] - 1) / (X.shape[0] - data_2.shape[1] - 1)

0.6676390577364661

In [51]:
0.6524214380655111 - 0.6676390577364661

-0.01521761967095503