In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_digits

In [3]:
digit = load_digits()

In [4]:
digit.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [5]:
digit.target

array([0, 1, 2, ..., 8, 9, 8])

In [6]:
digit.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
digit.images

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [8]:
df = pd.DataFrame(digit.data)
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [9]:
df['target'] = digit.target

In [10]:
df.head()

0    1    2     3     4     5    6    7    8    9  ...   55   56   57  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    58    59    60    61   62   63  target  
0  6.0  13.0  10.0   0.0  0.0  0.0       0  
1  0.0  11.0  16.0  10.0  0.0  0.0       1  
2  0.0   3.0  11.0  16.0  9.0  0.0       2  
3  7.0  13.0  13.0   9.0  0.0  0.0       3  
4  0.0   2.0  16.0   4.0  0.0  0.0       4  

[5 rows x 65 columns]

In [11]:
X = df.drop(['target'],axis=1)
y = df.target

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [13]:
X_train.head()

0    1     2     3     4     5    6    7    8    9   ...    54   55  \
428   0.0  0.0   0.0   1.0  12.0   7.0  0.0  0.0  0.0  0.0  ...   0.0  0.0   
1357  0.0  0.0   1.0  15.0  15.0   2.0  0.0  0.0  0.0  0.0  ...   0.0  0.0   
1185  0.0  1.0  12.0  15.0  16.0  13.0  1.0  0.0  0.0  4.0  ...   0.0  0.0   
31    0.0  0.0   2.0  13.0   8.0   0.0  0.0  0.0  0.0  0.0  ...  16.0  2.0   
1603  0.0  2.0  11.0  14.0  14.0   9.0  0.0  0.0  0.0  3.0  ...   0.0  0.0   

       56   57    58    59    60    61    62   63  
428   0.0  0.0   0.0   3.0  15.0  13.0   0.0  0.0  
1357  0.0  0.0   1.0  14.0  16.0   7.0   0.0  0.0  
1185  0.0  2.0  13.0  16.0  10.0   0.0   0.0  0.0  
31    0.0  0.0   2.0  15.0  13.0  14.0  13.0  2.0  
1603  0.0  1.0  15.0  13.0   1.0   0.0   0.0  0.0  

[5 rows x 64 columns]

In [14]:
X_test.head()

0    1     2     3     4     5    6    7    8    9   ...    54   55  \
1245  0.0  0.0   0.0   7.0  12.0   0.0  0.0  0.0  0.0  0.0  ...  16.0  2.0   
220   0.0  0.0  11.0  16.0   8.0   0.0  0.0  0.0  0.0  6.0  ...   0.0  0.0   
1518  0.0  0.0   8.0  15.0  12.0   4.0  0.0  0.0  0.0  5.0  ...   7.0  0.0   
438   0.0  0.0   2.0  12.0  12.0  12.0  9.0  2.0  0.0  0.0  ...   0.0  0.0   
1270  0.0  2.0  13.0  16.0  10.0   0.0  0.0  0.0  0.0  6.0  ...  14.0  0.0   

       56   57    58    59    60    61   62   63  
1245  0.0  0.0   0.0   9.0  14.0  14.0  5.0  0.0  
220   0.0  0.0  13.0  16.0  11.0   1.0  0.0  0.0  
1518  0.0  0.0  13.0  16.0  15.0   8.0  0.0  0.0  
438   0.0  0.0   3.0  15.0   3.0   0.0  0.0  0.0  
1270  0.0  3.0  15.0  16.0  16.0  10.0  1.0  0.0  

[5 rows x 64 columns]

In [15]:
y_train.head()

428     1
1357    1
1185    8
31      9
1603    3
Name: target, dtype: int32

In [16]:
y_test.head()

1245    6
220     9
1518    3
438     7
1270    2
Name: target, dtype: int32

In [17]:
len(X_train)

1203

In [18]:
len(X_test)

594

In [19]:
len(y_train)

1203

In [20]:
len(X_test)

594

In [21]:
from sklearn.svm import SVC

In [22]:
reg = SVC(kernel='linear')+

In [23]:
reg.fit(X_train,y_train)

SVC(kernel='linear')

In [24]:
y_train_pred = reg.predict(X_train)

In [25]:
y_train_pred[:10]

array([1, 1, 8, 9, 3, 4, 2, 9, 1, 7])

In [26]:
y_test_pred = reg.predict(X_test)


In [27]:
y_test_pred[:10]

array([6, 9, 3, 7, 2, 1, 5, 2, 5, 2])

In [28]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


### For Training Data

In [29]:
confusion_matrix(y_train,y_train_pred)

array([[123,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 127,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 125,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 127,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 117,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, 109,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 124,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 117,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 122,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 112]], dtype=int64)

In [30]:
reg.score(X_train,y_train)*100

100.0

In [31]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       123
           1       1.00      1.00      1.00       127
           2       1.00      1.00      1.00       125
           3       1.00      1.00      1.00       127
           4       1.00      1.00      1.00       117
           5       1.00      1.00      1.00       109
           6       1.00      1.00      1.00       124
           7       1.00      1.00      1.00       117
           8       1.00      1.00      1.00       122
           9       1.00      1.00      1.00       112

    accuracy                           1.00      1203
   macro avg       1.00      1.00      1.00      1203
weighted avg       1.00      1.00      1.00      1203



### For Test Data

In [32]:
confusion_matrix(y_test,y_test_pred)

array([[55,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 53,  0,  0,  1,  0,  0,  0,  1,  0],
       [ 0,  0, 52,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 54,  0,  1,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 64,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 71,  0,  1,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 57,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 61,  0,  1],
       [ 0,  1,  0,  1,  0,  1,  0,  0, 49,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0,  1, 66]], dtype=int64)

In [33]:
accuracy_score(y_test,y_test_pred)*100

97.97979797979798

In [34]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        55
           1       0.98      0.96      0.97        55
           2       1.00      1.00      1.00        52
           3       0.98      0.96      0.97        56
           4       0.97      1.00      0.98        64
           5       0.97      0.97      0.97        73
           6       1.00      1.00      1.00        57
           7       0.98      0.98      0.98        62
           8       0.94      0.94      0.94        52
           9       0.97      0.97      0.97        68

    accuracy                           0.98       594
   macro avg       0.98      0.98      0.98       594
weighted avg       0.98      0.98      0.98       594

